### ISSUE TITLE
Upcoming movies section still shows released movies

### ISSUE THREAD

**Issue by Olamatto** [bapspatil/SilverScreener#2]
#### Expected behavior
The upcoming section is meant to show movies  that are yet to be released only, not movies that have been released. 

#### Actual Behavior 
Some already released movies are still in the upcoming section. 

#### How to reproduce
- Download and install the application [here](https://play.google.com/store/apps/details?id=bapspatil.silverscreener&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)
- Switch on your data connection 
- Launch the application 
- Click on the Upcoming tab
- Check out some movies, looking at their release date,  some already released movies are still in the upcoming section. 

<hr>

Application version: v1.3.1
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/C8jrJ8YWNM0

**Comment by bapspatil** [comment]
That's an issue with the TMDB API. It provides outdated data.
